name: Build All

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  check_clang:
    name: Test clang,lldb,libclc
    uses: ./.github/workflows/llvm-project-tests.yml
    with:
    #   build_target: check-clang
      build_target:
      projects: clang;lldb;libclc;lld
      os_list: '["ubuntu-latest", "windows-latest", "macOS-11", "macOS-12", "macOS-latest"]'
